# Copyright (c) Weyl AI Research and Development, Inc. and affiliates.
#
# LLVM 22 C++ toolchain using hermetic Nix store paths.
#
# One toolchain for everything:
#   - Host C++ compilation (clang++)
#   - Device compilation (clang++ -x cuda)  
#   - Linking (lld)
#   - Archives (llvm-ar)
#
# Paths are read from .buckconfig.local, generated by `nix develop`.
# No wrappers. No PATH lookup. Just absolute Nix store paths.
#
# No GCC. No nvcc. Ever.

load(
    "@prelude//cxx:cxx_toolchain_types.bzl",
    "BinaryUtilitiesInfo",
    "CCompilerInfo",
    "CvtresCompilerInfo",
    "CxxCompilerInfo",
    "CxxPlatformInfo",
    "CxxToolchainInfo",
    "LinkerInfo",
    "LinkerType",
    "PicBehavior",
    "RcCompilerInfo",
    "ShlibInterfacesMode",
)
load("@prelude//cxx:headers.bzl", "HeaderMode")
load("@prelude//cxx:linker.bzl", "is_pdb_generated")
load("@prelude//linking:link_info.bzl", "LinkOrdering", "LinkStyle")
load("@prelude//linking:lto.bzl", "LtoMode")
load("@prelude//toolchains:cxx.bzl", "CxxToolsInfo")

def _run_info(args):
    return None if args == None else RunInfo(args = [args])

def _llvm_toolchain_impl(ctx: AnalysisContext) -> list[Provider]:
    """
    LLVM 22 toolchain with paths from .buckconfig.local.
    
    Reads [cxx] section for absolute Nix store paths:
      cc, cxx, ar, ld - tool paths
      clang_resource_dir, gcc_include, etc. - for include flags
    """
    
    # ════════════════════════════════════════════════════════════════════════════
    # Read tool paths from config (fall back to wrapper scripts)
    # Wrapper scripts (bin/clang, bin/clang++) inherit NIX_CFLAGS_COMPILE
    # ════════════════════════════════════════════════════════════════════════════
    cc = read_root_config("cxx", "cc", "bin/clang")
    cxx = read_root_config("cxx", "cxx", "bin/clang++")
    ar = read_root_config("cxx", "ar", "ar")
    ld = read_root_config("cxx", "ld", "ld")
    
    # ════════════════════════════════════════════════════════════════════════════
    # Build include flags from config paths
    # ════════════════════════════════════════════════════════════════════════════
    include_flags = []
    
    # Clang resource directory (for __stddef.h, etc.)
    clang_resource_dir = read_root_config("cxx", "clang_resource_dir", None)
    if clang_resource_dir:
        include_flags.append("-resource-dir=" + clang_resource_dir)
        include_flags.append("-isystem" + clang_resource_dir + "/include")
    
    # GCC libstdc++ headers
    gcc_include = read_root_config("cxx", "gcc_include", None)
    if gcc_include:
        include_flags.append("-isystem" + gcc_include)
    
    gcc_include_arch = read_root_config("cxx", "gcc_include_arch", None)
    if gcc_include_arch:
        include_flags.append("-isystem" + gcc_include_arch)
    
    # glibc headers
    glibc_include = read_root_config("cxx", "glibc_include", None)
    if glibc_include:
        include_flags.append("-isystem" + glibc_include)
    
    # mdspan (Kokkos reference implementation, until libstdc++ ships it)
    mdspan_include = read_root_config("cxx", "mdspan_include", None)
    if mdspan_include:
        include_flags.append("-isystem" + mdspan_include)
    
    # ════════════════════════════════════════════════════════════════════════════
    # Build link flags from config paths
    # ════════════════════════════════════════════════════════════════════════════
    extra_link_flags = []  # Use default linker from PATH
    
    # glibc_lib: contains CRT files (Scrt1.o, crti.o, crtn.o) and libc, libm, libpthread
    glibc_lib = read_root_config("cxx", "glibc_lib", None)
    if glibc_lib:
        # -B tells clang where to find CRT files
        extra_link_flags.append("-B" + glibc_lib)
        extra_link_flags.append("-L" + glibc_lib)
        extra_link_flags.append("-Wl,-rpath," + glibc_lib)
    
    # gcc_lib: contains crtbeginS.o, crtendS.o, libgcc.a, libgcc_s.so
    gcc_lib = read_root_config("cxx", "gcc_lib", None)
    if gcc_lib:
        extra_link_flags.append("-B" + gcc_lib)
        extra_link_flags.append("-L" + gcc_lib)
        extra_link_flags.append("-Wl,-rpath," + gcc_lib)
    
    # gcc_lib_base: contains libstdc++.so
    gcc_lib_base = read_root_config("cxx", "gcc_lib_base", None)
    if gcc_lib_base:
        extra_link_flags.append("-L" + gcc_lib_base)
        extra_link_flags.append("-Wl,-rpath," + gcc_lib_base)
    
    # ════════════════════════════════════════════════════════════════════════════
    # Combine with user-provided flags
    # ════════════════════════════════════════════════════════════════════════════
    c_flags = include_flags + ctx.attrs.c_flags
    cxx_flags = include_flags + ctx.attrs.cxx_flags
    link_flags = extra_link_flags + ctx.attrs.link_flags
    
    # ════════════════════════════════════════════════════════════════════════════
    # Build the toolchain provider
    # ════════════════════════════════════════════════════════════════════════════
    return [
        DefaultInfo(),
        CxxToolchainInfo(
            mk_comp_db = ctx.attrs.make_comp_db,
            linker_info = LinkerInfo(
                linker = _run_info(cxx),
                linker_flags = link_flags,
                post_linker_flags = [],
                archiver = _run_info(ar),
                archiver_type = "gnu",
                archiver_supports_argfiles = True,
                generate_linker_maps = False,
                lto_mode = LtoMode("none"),
                type = LinkerType("gnu"),
                link_binaries_locally = True,
                link_libraries_locally = True,
                archive_objects_locally = True,
                use_archiver_flags = True,
                static_dep_runtime_ld_flags = [],
                static_pic_dep_runtime_ld_flags = [],
                shared_dep_runtime_ld_flags = [],
                independent_shlib_interface_linker_flags = [],
                shlib_interfaces = ShlibInterfacesMode("disabled"),
                link_style = LinkStyle(ctx.attrs.link_style),
                link_weight = 1,
                binary_extension = "",
                object_file_extension = "o",
                shared_library_name_default_prefix = "lib",
                shared_library_name_format = "{}.so",
                shared_library_versioned_name_format = "{}.so.{}",
                static_library_extension = "a",
                force_full_hybrid_if_capable = False,
                is_pdb_generated = False,
                link_ordering = None,
            ),
            bolt_enabled = False,
            binary_utilities_info = BinaryUtilitiesInfo(
                nm = RunInfo(args = ["llvm-nm"]),
                objcopy = RunInfo(args = ["llvm-objcopy"]),
                objdump = RunInfo(args = ["llvm-objdump"]),
                ranlib = RunInfo(args = ["llvm-ranlib"]),
                strip = RunInfo(args = ["llvm-strip"]),
                dwp = None,
                bolt_msdk = None,
            ),
            cxx_compiler_info = CxxCompilerInfo(
                compiler = _run_info(cxx),
                preprocessor_flags = [],
                compiler_flags = cxx_flags,
                compiler_type = "clang",
            ),
            c_compiler_info = CCompilerInfo(
                compiler = _run_info(cc),
                preprocessor_flags = [],
                compiler_flags = c_flags,
                compiler_type = "clang",
            ),
            as_compiler_info = CCompilerInfo(
                compiler = _run_info(cc),
                compiler_type = "clang",
            ),
            asm_compiler_info = CCompilerInfo(
                compiler = _run_info(cc),
                compiler_type = "clang",
            ),
            cvtres_compiler_info = CvtresCompilerInfo(
                compiler = None,
                preprocessor_flags = [],
                compiler_flags = [],
                compiler_type = "clang",
            ),
            rc_compiler_info = RcCompilerInfo(
                compiler = None,
                preprocessor_flags = [],
                compiler_flags = [],
                compiler_type = "clang",
            ),
            header_mode = HeaderMode("symlink_tree_only"),
            cpp_dep_tracking_mode = "makefile",
            pic_behavior = PicBehavior("supported"),
            llvm_link = RunInfo(args = ["llvm-link"]),
        ),
        CxxPlatformInfo(name = "x86_64"),
    ]

llvm_toolchain = rule(
    impl = _llvm_toolchain_impl,
    attrs = {
        "c_flags": attrs.list(attrs.string(), default = []),
        "cxx_flags": attrs.list(attrs.string(), default = []),
        "link_flags": attrs.list(attrs.string(), default = []),
        "link_style": attrs.string(default = "static"),
        "make_comp_db": attrs.default_only(attrs.exec_dep(providers = [RunInfo], default = "prelude//cxx/tools:make_comp_db")),
    },
    is_toolchain_rule = True,
)
